/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 choco1.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const groupRef = useRef()
  props.animated(groupRef)
  const { nodes, materials } = useGLTF('/bergamot.gltf')
  return (
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Chocolate002.geometry} material={materials['Chocolate Verde.002']} />
    </group>
  )
}

useGLTF.preload('/bergamot.gltf')
