/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 burnt_caramel.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/burnt_caramel.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Chocolate.geometry} material={materials['Chocolate Verde.001']} />
    </group>
  )
}

useGLTF.preload('/burnt_caramel.gltf')
