/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 celular.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'

export default function Chocolate1(props) {
  const groupRef = useRef()
  useFrame(()=>{
    if(groupRef.current){
      groupRef.current.rotation.y+=0.003
    }
  })
  const { nodes, materials } = useGLTF('/celular.gltf')
  return (
    <group {...props} ref={groupRef} dispose={null}>
      <mesh geometry={nodes.SmartPhone_Body.geometry} material={materials['SmartPhone_back.001']} rotation={[Math.PI / 2, 0, 0]} scale={[0.012, 0.005, 0.013]}>
        <mesh geometry={nodes.SmartPhone_back.geometry} material={materials['SmartPhone_back.001']} position={[1.455, -0.485, -9.432]} rotation={[-Math.PI, 0, 0]} scale={[0.032, 0.065, 0.03]} />
        <group position={[1.891, -0.693, -9.853]} rotation={[-Math.PI, 0, 0]} scale={[6.969, 16.409, 6.436]}>
          <mesh geometry={nodes.Cylinder001.geometry} material={materials['SmartPhone_Glass_camera_small_in.001']} />
          <mesh geometry={nodes.Cylinder001_1.geometry} material={materials['SmartPhone_camera_in_edge_A.001']} />
          <mesh geometry={nodes.Cylinder001_2.geometry} material={materials['SmartPhone_camera_in_edge_B.001']} />
        </group>
        <group position={[1.891, -0.693, -8.766]} rotation={[-Math.PI, 0, 0]} scale={[6.969, 16.409, 6.436]}>
          <mesh geometry={nodes.Cylinder025.geometry} material={materials['SmartPhone_Glass_camera_small_in.001']} />
          <mesh geometry={nodes.Cylinder025_1.geometry} material={materials['SmartPhone_camera_in_edge_A.001']} />
          <mesh geometry={nodes.Cylinder025_2.geometry} material={materials['SmartPhone_camera_in_edge_B.001']} />
        </group>
        <mesh geometry={nodes.SmartPhone_edge_camera_base.geometry} material={materials['SmartPhone_back.001']} position={[1.901, -0.503, -9.314]} scale={[5.814, 13.69, 5.37]} />
        <mesh geometry={nodes.SmartPhone_edge_camera001.geometry} material={materials['SmartPhone_Small camera edge.002']} position={[1.891, -0.533, -9.853]} rotation={[-Math.PI, 0, 0]} scale={[6.387, 8.526, 5.899]} />
        <mesh geometry={nodes.SmartPhone_edge_camera002.geometry} material={materials['SmartPhone_Small camera edge.002']} position={[1.891, -0.533, -8.758]} rotation={[-Math.PI, 0, 0]} scale={[6.387, 8.526, 5.899]} />
        <group position={[1.45, -0.414, -9.267]} rotation={[-Math.PI, 0, 0]} scale={[0.082, 0.194, 0.076]}>
          <mesh geometry={nodes.Cylinder012.geometry} material={materials.SmartPhone_flash_yellow} />
          <mesh geometry={nodes.Cylinder012_1.geometry} material={materials.SmartPhone_flash_white} />
        </group>
        <mesh geometry={nodes.SmartPhone_Glass_camera001.geometry} material={materials.SmartPhone_Glass_camera_in001} position={[1.891, -0.671, -9.853]} rotation={[-Math.PI, 0, 0]} scale={[7.492, 17.642, 6.92]} />
        <mesh geometry={nodes.SmartPhone_Glass_camera002.geometry} material={materials.SmartPhone_Glass_camera_in001} position={[1.891, -0.671, -8.744]} rotation={[-Math.PI, 0, 0]} scale={[7.492, 17.642, 6.92]} />
        <mesh geometry={nodes.SmartPhone_Glass_Back_camera.geometry} material={materials['SmartPhone_Glass_camera_Smartphone.Big']} position={[1.901, -0.75, -9.314]} scale={[5.993, 14.113, 5.536]} />
        <group position={[0.006, 0.373, -8.349]}>
          <mesh geometry={nodes.Plane007.geometry} material={materials['SmartPhone_back.001']} />
          <mesh geometry={nodes.Plane007_1.geometry} material={materials.SmartPhone_Screnn} />
          <mesh geometry={nodes.Plane007_2.geometry} material={materials.SmartPhone_Speaker} />
        </group>
        <mesh geometry={nodes.SmartPhone_Switch001.geometry} material={materials['SmartPhone_back.001']} position={[-2.958, -0.01, -8.753]} rotation={[-Math.PI / 2, 0, 0]} scale={[4.777, 2.283, 10.136]} />
        <mesh geometry={nodes.SmartPhone_Switch002.geometry} material={materials['SmartPhone_back.001']} position={[-2.95, 0, -7.648]} rotation={[-Math.PI / 2, 0, 0]} scale={[5.814, 5.37, 13.69]} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/celular.gltf')
