/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 caja2.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/caja2.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.White} position={[-0.177, -0.004, 0.438]} rotation={[-0.21, 0, 0]} scale={[3.13, 0.855, 0.855]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Plastic} position={[-0.071, 0.059, -0.072]} rotation={[-0.21, 0, 0]} scale={[2.433, 0.635, 0.451]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.White} position={[-0.177, -0.805, 0.608]} rotation={[-0.21, 0, 0]} scale={[3.13, 0.855, 0.855]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials.Plastic} position={[-0.071, 0.846, 0.24]} rotation={[-0.21, 0, 0]} scale={[2.433, 0.635, 0.451]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Transparent Glass']} position={[-0.071, 0.846, 0.24]} rotation={[-0.21, 0, 0]} scale={[2.433, 0.635, 0.451]} />
    </group>
  )
}

useGLTF.preload('/caja2.gltf')
