/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 caja3.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/caja3.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube002.geometry} material={materials.Plastic} position={[-0.071, 0.872, 0.272]} rotation={[-0.164, 0, 0]} scale={[2.617, 0.635, 0.451]} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Plastic} position={[-0.071, 0.1, -0.075]} rotation={[-0.164, 0, 0]} scale={[2.617, 0.635, 0.451]} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Transparent plastic']} position={[0.243, -0.699, 0.426]} rotation={[1.413, 0, 0]} scale={[2.618, 2.727, 2.673]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Transparent Glass']} position={[-0.071, 0.872, 0.272]} rotation={[-0.164, 0, 0]} scale={[2.617, 0.635, 0.451]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Black} position={[-0.071, 0.1, -0.044]} rotation={[-0.164, 0, 0]} scale={[2.587, 0.621, 0.451]} />
    </group>
  )
}

useGLTF.preload('/caja3.gltf')
